# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create a directory for the app
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose port if needed (not specified in MCP, but leaving open)

# Start the server
CMD ["node", "build/index.js"]
